### ISSUE TITLE
error handler for bad or missing code

### ISSUE THREAD

**Issue by Jaymzu** [bogde/xbmc.serialepenet.ro#6]
Ehlo, 

Is there an error message implemented for situations where the serial/code required to use the service is missing or too many devices attached ? The behaviour on my system (OSX XBMC nightly build) is crash when the code/serial is missing

**Comment by bogde** [comment]
the plugin tries to show the episode in "free" mode (serialepenet.ro usually allows you to to watch a couple(?) episodes). if the website rejects the requests, it should show a message about a code being required. should do the same for wrong codes.

i doubt serialepenet keeps track of the number of devices using the same code, especially if we're talking about devices sharing the same ip (for instance in a home network). i dont have any facts on that though.

the xbmc.log should help tracking down the issue.
