### ISSUE TITLE
salut

### ISSUE THREAD

**Issue by alaltaieri** [bogde/xbmc.serialepenet.ro#7]
Salut. Vroiam sa iti multumesc pentru ca ai creeat asemenea plugin. Este excelent. Totusi se pare ca are ceva probleme. Am bagat cod de activare dar pe apple tv 2 cam 2 din 3 incercari iese inapoi pe home screen. Cateodata iese direct cand intru in aplicatie alta data cand intru pur si simplu pe o categorie de seriale.
Alte dati spune ca trebuie bagat codul(desi este bagat). Daca ma duc la activare si dau done din nou si revin sa caut un serial, merge.
Nu stiu sincer daca facea asa si inainte de a baga acel cod de activare pentru ca l-am bagat direct si nu am testat inainte(fara cod).
Daca ai avea timp vreodata sa te mai uiti pe el ar fi excelent :)

Inca odata multumesc pentru un astfel de plugin. Sunt destui de putini care se incumeta sa faca pluginuri xbmc pt asa ceva.

Cristi

**Comment by bogde** [comment]
merci pentru aprecieri.

problema e ca nu am un apple tv si imi e imposibil sa testez. eu l-am testat pe raspberry pi, pe windows 7 si pe osx 10.9. cel putin o alta persoana l-a folosit pe mac os. ce vreau sa spun e ca in principiu functioneaza, pe rPi noi il folosim zilnic, si mi-e greu sa incerc sa repar ceva ce ... merge.

daca imi trimiti fisierul xbmc.log, ma voi uita peste el. pe raspberry e in /home/pi/.xbmc/temp/ iar pe mac os in /Users/USERNAME/Library/Logs/. nu stiu unde e in appletv... de asemenea sa-mi zici daca folosesti branch-ul master sau macos.

**Comment by alaltaieri** [comment]
Vad ca nu mai da erori dupa ce l-am mai butonat putin. Doar ca merge greoi. eh, cu asta o sa ma obisnuiesc pe parcurs :)  Nu stiu ce inseamna branch-ul master sau macos. Il folosesc pe apple tv..care este macOS.

Pe windows 7 in schimb, pe xbmc 12.3 frodo se mai inteapa (not responding) si se inchide doar cu end task :) (ai aici logul: http://pastebin.com/LUGJT9ak  am mai taiat din el. o sa vezi 3:43 iar apoi 4:20, este perioada cat m-am uitat la un serial. dupa ce am iesit din el s-a blocat.)

ps: am incercat si cu frodo 12.2 si tot asa face. de obicei se blocheaza de tot ori cand ies dintr-un video si dau back sa ma duc la alt episod sau pur si simplu cand caut printre episoade,intru in sezoane etc.

Mersi

**Comment by bogde** [comment]
Cand downloadezi de pe github exista o "versiune" (branch) master (varianta
initiala pe care am facut-o) si una macos, care e o versiune modificata
pentru ca din cauza unui bug de care suferea varianta de xbmc pentru mac
branch-ul master nu functiona. Cred ca ai downloadat versiunea master,
probabil in xbmc-ul de pe apple tv s-a reparat bug-ul de care zic. Poate
chiar zilele astea si s-a facut update si de aia merge.

**Comment by alaltaieri** [comment]
Mersi de raspuns si de suport :)
Editasem mesajul azi noapte cu problemele pe care le am in windows 7 dar vad ca nu a mai aparut in quote.
oricum, asta scrisesem " Pe windows 7 in schimb, pe xbmc 12.3 frodo se mai inteapa (not responding) si se inchide doar cu end task :) (ai aici logul: http://pastebin.com/LUGJT9ak am mai taiat din el. o sa vezi 3:43 iar apoi 4:20, este perioada cat m-am uitat la un serial. dupa ce am iesit din el s-a blocat.)"

Mersi
